FROM centos:7
MAINTAINER {code} by Dell EMC project-rexray SLACK channel <http://community.emccode.com>

RUN rpm -i https://emccode.bintray.com/rexray/stable/0.7.0/rexray-controller-0.7.0-1.x86_64.rpm

CMD [“rexray-controller”, “start”, “-f”]