FROM centos:7
MAINTAINER {code} by Dell EMC <http://community.emccode.com>

RUN rpm -i https://emccode.bintray.com/rexray/staged/0.7.0-rc6/rexray-controller-0.7.0+rc6-1.x86_64.rpm

CMD [“rexray-controller”, “start”, “-f”]